import img from 'src/assets/img/defaultCardImage.jpeg';

export const DEFAULT_CARDS = [
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
    {
        title: 'Assassin’s Creed',
        rating: 5,
        description: 'There are growing dangers in the wizarding world of 1926 New York and assassins',
        genre: ['Экшен', 'Фантастика', 'Приключения'],
        imgSrc: img,
        filmId: 1,
    },
];
